### ISSUE TITLE
configreader.py does not support python 2

### ISSUE THREAD

**Issue by rwarren** [takluyver/pynsist#46] opened 2015-04-15 17:09 UTC
I just tried pynsist on debian, running python 2.7.3.

The first thing I thought I would try was building the examples with `examples/build_all_examples.py`.  It fails immediately.

The first crash happens immediately in `configreader.py` due to the use of the python3-only `interpolation` argument on `ConfigParser`.

Fixing this, the second crash is on the attempted use of `__getitem__` with `config[section_name]`... also a python3-only thing.

Sorry - I have no time right now to fix this or diagnose further.  I fear the python2 issues run deep since the top level example fails so immediately.  I was hoping `pynsist` would work as it would be nice to stay in debian rather than having to jump over to windows all the time to make installers (currently doing this with `cx_freeze`). :(

**Comment by takluyver** [comment] 2015-04-15 17:13
Install [configparser](https://pypi.python.org/pypi/configparser) from PyPI. This should have been automatically installed if you installed pynsist with pip.

**Comment by rwarren** [comment] 2015-04-15 17:27
Strange, I already have the latest `configparser`.  Not sure why it is complaining.  I'll look into it.

Here's the traceback:

    $ pip freeze | grep configparser
    configparser==3.3.0r2
    $ python ./build_all_examples.py 
    Traceback (most recent call last):
      File "./build_all_examples.py", line 18, in <module>
        nsist.main([example_cfg])
      File "/home/russ/code/github/pynsist/nsist/__init__.py", line 393, in main
        cfg = configreader.read_and_validate(config_file)
      File "/home/russ/code/github/pynsist/nsist/configreader.py", line 96, in read_and_validate
        config = configparser.ConfigParser(interpolation=None)
    TypeError: __init__() got an unexpected keyword argument 'interpolation'

**Comment by rwarren** [comment] 2015-04-15 17:29
Paths are because install method was to fork, clone, and then `pip install -e`.

**Comment by takluyver** [comment] 2015-04-15 18:44
Stick a `print(configparser)` in the code and see where it's loading that module from. I've just checked on Python 2 and I can instantiate it OK.

**Comment by rwarren** [comment] 2015-04-15 19:12
Something is seriously amiss, and it seems to be due to requests somehow.  It's hijacking the import process in some way.

I'm running this inside a virtualenv.  configparser is installed properly in the virtualenv.  The configparser module is from the correct virtualenv path, but the atcual ConfigParser object is being imported from the **system** python in `/usr/lib/python2,7`.  That is seriously messed up.

Stepping through with a debugger shows some weird import hijacking through `site-packages/requests/packages . VendorAlias.findmodule`.

Are you intentionally doing some weirdness there?

**Comment by takluyver** [comment] 2015-04-15 19:25
I'm not doing any weirdness. requests is doing something strange, but it doesn't look like it should affect configparser. The code for that is here: https://github.com/kennethreitz/requests/blob/master/requests/packages/__init__.py

**Comment by rwarren** [comment] 2015-04-15 19:40
Yep... was stepping through that code in the debugger.  It may not *look* strange, but the fact that I end up stepping through there (a few times) during your `import configparser` definitely *is* strange. :)

Here is the local stacktrace that has me scratching my head during the import:

      File "/home/russ/code/github/pynsist/examples/build_all_examples.py", line 18, in <module>
        nsist.main([example_cfg])
      File "/home/russ/code/github/pynsist/nsist/__init__.py", line 392, in main
        from . import configreader
      File "/home/russ/code/github/pynsist/nsist/configreader.py", line 3, in <module>
        import configparser
      File "/home/russ/.virtualenvs/edms/local/lib/python2.7/site-packages/requests/packages/__init__.py", line 39, in find_module
        if fullname.startswith(self._vendor_pkg):

And here is a stacktrace that shows the inexplicable/scary virtualenv jailbreak out into system python:

      File "/home/russ/code/github/pynsist/examples/build_all_examples.py", line 18, in <module>
        nsist.main([example_cfg])
      File "/home/russ/code/github/pynsist/nsist/__init__.py", line 392, in main
        from . import configreader
      File "/home/russ/code/github/pynsist/nsist/configreader.py", line 3, in <module>
        import configparser
      File "/home/russ/.virtualenvs/edms/local/lib/python2.7/site-packages/configparser/__init__.py", line 5, in <module>
        from ConfigParser import *
      File "/usr/lib/python2.7/ConfigParser.py", line 90, in <module>
        try:

I have NEVER seen that before and it is a bit scary.  The requests thing may e a red herring, but like I say, something is clearly amiss with the import system here.  So much so that I assumed you were doing something... need to look further.

Need to leave this for now... lost too much time as-is.  I will try and return to it later.

**Comment by takluyver** [comment] 2015-04-15 19:47
The line in your `.../configparser/__init__.py` doesn't appear to be part of the backported configparser module - it looks like you may have something else installed that is providing that package, and the imports are finding that instead of the backport, which on my system is a single `configparser.py` module.

I think the requests stuff is a red herring: it adds an entry to sys.meta_path, so it will be checked on each import, even if it doesn't get used.

**Comment by rwarren** [comment] 2015-04-15 19:58
Not sure what else I can do other than uninstall and reinstall configparser, which I've done a few times.

In a nutshell:

    >>> from backports import configparser
    Traceback (most recent call last):
      File "<input>", line 1, in <module>
    ImportError: cannot import name configparser
    >>> import configparser
    >>> import ConfigParser
    >>> configparser.ConfigParser is ConfigParser.ConfigParser
    True
    >>> print "Argh!"
    Argh!

**Comment by takluyver** [comment] 2015-04-15 21:01
Manually delete that directory? If it's not part of the configparser module, it won't be uninstalled by `pip uninstall configparser`.

**Comment by takluyver** [comment] 2015-04-15 21:01
Sorry, that should be "...if it's not part of the configparser *distribution*"

**Comment by rwarren** [comment] 2015-04-15 21:40
Success!!  I should have thought of deleting that dir... thanks for the help!

I've built several of the example now... looks good.

However, I've just seen that the installation method is to clearly install python and launch from there, rather than make that invisible to the end user.  I now see that this is plainly stated in your documentation under disadvantages, so that should be no surprise to me. I missed it until this moment, though... :(

Any future plans on going the transparent route of the other installer solutions?

Way off topic... should just close this issue...

**Comment by takluyver** [comment] 2015-04-16 02:21
For now, I'm sticking with the approach of installing Python as a framework, rather than bundling it in each app. This will have a very nice benefit when Python 3.5 comes out - it will be possible to bundle the new network installers, cutting ~24 MB off the size of an application installer, and it will download the extra components at install time if they're not already there.

Python is not very visible to users in recent versions of Windows: the easiest way to use the start menu is to start typing the name of a program you want, in which case you don't see much of things you're not using. There might be an option in the future to install without start menu shortcuts, in which case I'd do that.

Steve Dower is talking about having a Python build on Windows that's just a zip folder - relocatable with no need to install. If that happens, I'd probably be open to making an option to bundle Python with the application instead of installing it.

I will close this issue, because the actual problem is not a bug, but that doesn't prevent comments, so feel free to keep using it as a dicussion thread, since there isn't yet a mailing list or anything for that.

**Closed** 2015-04-16 02:21 UTC
